---
title: "SampleQ Help"
author: "Patrick Eslick"
date: "March 9, 2018"
---

### What this app does

This app gets a list of sample start times from the [QW NWIS web service](https://nwis.waterdata.usgs.gov/nwis/qwdata), along with any discharge (Q) and gage height (GHT) measurements associated with the sample in QWDATA. The sample start times are then used to interpolate a value for discharge and gage height between the continuous time series points immediately before and after the sample. The app can also be used to find the discharge and gage height time series points closes in time to the reported sample time.

### Using the app

1. Type the USGS site number in the **Location** box.
2. Type (or select) start and end dates in the Dates boxes.
3. Select the maximum gap to use for interpolation. Time series values will only be interpolated if there are two points before and after the sample that are within this many hours of each other.
4. Select the method used to merge the sample times with the discharge and gage height data. By default, the app will interpolate between the two closest points. The other option is to simply use the closest time series point to each sample time.
5. Click "Get data" to display results.
6. Click "Download" to download a csv file of the results.

### Headings in the output file

**datetime** - the start time of the sample from the NWIS web service  
**QW_Q** - the discharge associated with the sample from the [QW NWIS web service](https://nwis.waterdata.usgs.gov/nwis/qwdata)    
**QW_GHT** - the gage height associated with the sample in QW NWIS web service  
**datetime_TS** - this column will be included if the "Use closest time series point" option is selected. This indicates the date and time of the nearest time series point to the sample  
**TS_Q** - the discharge interpolated (if using interpolation) from the continuous discharge time series on the [NWIS web service](https://waterservices.usgs.gov/)  
**TS_GHT** - the gage height interpolated (if using interpolation) from the continuous gage height time series on the NWIS web service
